default = false
release_mode = false

# default DEBUG, DEBUG INFO WARN ERROR OFF
log_level = "DEBUG"

# REDIS,FILE,COOKIE(COOKIE Default)
session_store = "REDIS"

# REDIS,MEMCACHED,IN_MEMORY(IN_MEMORY Default)
cache_store = "REDIS"

[app]
name = "Manu Cutillas Personal website"

[server]
graceful = true
addr = ":8080"

# Domains
domain_api = "echo.api.localhost.com"
domain_web = "echo.www.localhost.com"
domain_socket = "echo.socket.localhost.com"

[static]
# BINDATA,FILE(FILE Default)
type = "BINDATA"

[tmpl]
# .html,.tpl
suffix = ".html"

[database]
name = "golang_db"
user_name = "golang_dba"
pwd  = "123456"
host = "127.0.0.1"
port = "3306"

[redis]
server = "127.0.0.1:6379"
pwd = "123456"


# jaeger serviceName
service_name = "Manu Cutillas Personal website"

# jaeger-agent 127.0.0.1:6831
# appdash http://localhost:8700
address = "127.0.0.1:6831"