package models
/*
"imagen_original": "fotografias\/articulos\/2016\/04\/kalypso-agency-evernote-se-une-a-linkedin-para-ayudarte-gestionar-tus-contactos-a-traves-de-tus-tarjetas-de-visita-original-uE.jpeg",
"imagen_large_1600_es": null,
"imagen_large_1024_es": "fotografias\/articulos\/2016\/04\/kalypso-agency-evernote-se-une-a-linkedin-para-ayudarte-gestionar-tus-contactos-a-traves-de-tus-tarjetas-de-visita-1024-uE.jpeg",
"imagen_medium_800_es": "fotografias\/articulos\/2016\/04\/kalypso-agency-evernote-se-une-a-linkedin-para-ayudarte-gestionar-tus-contactos-a-traves-de-tus-tarjetas-de-visita-800-uE.jpeg",
"imagen_medium_640_es": "fotografias\/articulos\/2016\/04\/kalypso-agency-evernote-se-une-a-linkedin-para-ayudarte-gestionar-tus-contactos-a-traves-de-tus-tarjetas-de-visita-640-uE.jpeg",
"imagen_medium_500_es": "fotografias\/articulos\/2016\/04\/kalypso-agency-evernote-se-une-a-linkedin-para-ayudarte-gestionar-tus-contactos-a-traves-de-tus-tarjetas-de-visita-500-uE.jpeg",
"imagen_tiny_320_es": "fotografias\/articulos\/2016\/04\/kalypso-agency-evernote-se-une-a-linkedin-para-ayudarte-gestionar-tus-contactos-a-traves-de-tus-tarjetas-de-visita-320-uE.jpeg",
"imagen_tiny_240_es": "fotografias\/articulos\/2016\/04\/kalypso-agency-evernote-se-une-a-linkedin-para-ayudarte-gestionar-tus-contactos-a-traves-de-tus-tarjetas-de-visita-240-uE.jpeg",
"imagen_square_150_es": "fotografias\/articulos\/2016\/04\/kalypso-agency-evernote-se-une-a-linkedin-para-ayudarte-gestionar-tus-contactos-a-traves-de-tus-tarjetas-de-visita-150-uE.jpeg",
"imagen_square_75_es": "fotografias\/articulos\/2016\/04\/kalypso-agency-evernote-se-une-a-linkedin-para-ayudarte-gestionar-tus-contactos-a-traves-de-tus-tarjetas-de-visita-75-uE.jpeg",
"imagen_miniature_100_es": "fotografias\/articulos\/2016\/04\/kalypso-agency-evernote-se-une-a-linkedin-para-ayudarte-gestionar-tus-contactos-a-traves-de-tus-tarjetas-de-visita-100-uE.jpeg",
"imagen_large_1600_en": null,
"imagen_large_1024_en": "fotografias\/articulos\/2016\/04\/kalypso-agency--1024-uE.jpeg",
"imagen_medium_800_en": "fotografias\/articulos\/2016\/04\/kalypso-agency--800-uE.jpeg",
"imagen_medium_640_en": "fotografias\/articulos\/2016\/04\/kalypso-agency--640-uE.jpeg",
"imagen_medium_500_en": "fotografias\/articulos\/2016\/04\/kalypso-agency--500-uE.jpeg",
"imagen_tiny_320_en": "fotografias\/articulos\/2016\/04\/kalypso-agency--320-uE.jpeg",
"imagen_tiny_240_en": "fotografias\/articulos\/2016\/04\/kalypso-agency--240-uE.jpeg",
"imagen_square_150_en": "fotografias\/articulos\/2016\/04\/kalypso-agency--150-uE.jpeg",
"imagen_square_75_en": "fotografias\/articulos\/2016\/04\/kalypso-agency--75-uE.jpeg",
"imagen_miniature_100_en": "fotografias\/articulos\/2016\/04\/kalypso-agency--100-uE.jpeg",
*/